<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 public/glb/male.glb --output src/models/male.svelte --types --keepnames --meta --shadows --debug
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type ActionName =
    | 'Man_Clapping'
    | 'Man_Death'
    | 'Man_Idle'
    | 'Man_Jump'
    | 'Man_Punch'
    | 'Man_Roll'
    | 'Man_Run'
    | 'Man_RunningJump'
    | 'Man_Sitting'
    | 'Man_Standing'
    | 'Man_SwordSlash'
    | 'Man_Walk'
  type GLTFResult = {
    nodes: {
      Cylinder002: THREE.SkinnedMesh
      Cylinder002_1: THREE.SkinnedMesh
      Cylinder002_2: THREE.SkinnedMesh
      Cylinder002_3: THREE.SkinnedMesh
      Cylinder002_4: THREE.SkinnedMesh
      Cylinder002_5: THREE.SkinnedMesh
      Bone: THREE.Bone
    }
    materials: {
      Skin: THREE.MeshStandardMaterial
      Eyes: THREE.MeshStandardMaterial
      Hair: THREE.MeshStandardMaterial
      Shirt: THREE.MeshStandardMaterial
      Pants: THREE.MeshStandardMaterial
      Socks: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/male.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

{#if $gltf}
  <T is={ref} dispose={false} {...$$restProps}>
    <T.Group name="Scene">
      <T.Group name="HumanArmature" userData={{ name: 'HumanArmature' }}>
        <T is={$gltf.nodes.Bone} />
        <T.Group name="BaseHuman" userData={{ name: 'BaseHuman' }}>
          <T.SkinnedMesh
            name="Cylinder002"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002.geometry}
            material={$gltf.materials.Skin}
            skeleton={$gltf.nodes.Cylinder002.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder002_1"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002_1.geometry}
            material={$gltf.materials.Eyes}
            skeleton={$gltf.nodes.Cylinder002_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder002_2"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002_2.geometry}
            material={$gltf.materials.Hair}
            skeleton={$gltf.nodes.Cylinder002_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder002_3"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002_3.geometry}
            material={$gltf.materials.Shirt}
            skeleton={$gltf.nodes.Cylinder002_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder002_4"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002_4.geometry}
            material={$gltf.materials.Pants}
            skeleton={$gltf.nodes.Cylinder002_4.skeleton}
          />
          <T.SkinnedMesh
            name="Cylinder002_5"
            castShadow
            receiveShadow
            geometry={$gltf.nodes.Cylinder002_5.geometry}
            material={$gltf.materials.Socks}
            skeleton={$gltf.nodes.Cylinder002_5.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>

    <slot {ref} />
  </T>
{/if}
