<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 public/glb/ship.glb --output src/models/ship.svelte --types --keepnames --meta --shadows --debug
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      sphere: THREE.Mesh
      sphere_band: THREE.Mesh
      person: THREE.Mesh
      exterior_top: THREE.Mesh
      exterior_bottom: THREE.Mesh
      exterior_middle_bottom: THREE.Mesh
      floor_top: THREE.Mesh
      floor_center: THREE.Mesh
      stasis_chamber: THREE.Mesh
      floor_bottom: THREE.Mesh
      exterior_middle_top: THREE.Mesh
      floor_top_railing: THREE.Mesh
      console: THREE.Mesh
      console_screen: THREE.Mesh
      ladder: THREE.Mesh
      elevator_platform: THREE.Mesh
      sentry: THREE.Mesh
      outer_collider_3_1: THREE.Mesh
      outer_collider_3_2: THREE.Mesh
      outer_collider_3_3: THREE.Mesh
      outer_collider_3_4: THREE.Mesh
      outer_collider_3_5: THREE.Mesh
      outer_collider_3_6: THREE.Mesh
      outer_collider_3_7: THREE.Mesh
      outer_collider_3_8: THREE.Mesh
      outer_collider_3_9: THREE.Mesh
      outer_collider_3_10: THREE.Mesh
      outer_collider_3_11: THREE.Mesh
      outer_collider_3_12: THREE.Mesh
      outer_collider_3_13: THREE.Mesh
      outer_collider_3_14: THREE.Mesh
      outer_collider_3_15: THREE.Mesh
      outer_collider_3_16: THREE.Mesh
      collider_rail_1: THREE.Mesh
      collider_rail_2: THREE.Mesh
      collider_rail_3: THREE.Mesh
      collider_rail_4: THREE.Mesh
      collider_rail_5: THREE.Mesh
      collider_rail_6: THREE.Mesh
      collider_rail_7: THREE.Mesh
      collider_rail_8: THREE.Mesh
      collider_rail_9: THREE.Mesh
      collider_rail_10: THREE.Mesh
      collider_rail_11: THREE.Mesh
      collider_rail_12: THREE.Mesh
      collider_rail_13: THREE.Mesh
      collider_rail_14: THREE.Mesh
      outer_collider_2_1: THREE.Mesh
      outer_collider_2_2: THREE.Mesh
      outer_collider_2_3: THREE.Mesh
      outer_collider_2_4: THREE.Mesh
      outer_collider_2_5: THREE.Mesh
      outer_collider_2_6: THREE.Mesh
      outer_collider_2_7: THREE.Mesh
      outer_collider_2_8: THREE.Mesh
      outer_collider_2_9: THREE.Mesh
      outer_collider_2_10: THREE.Mesh
      outer_collider_2_11: THREE.Mesh
      outer_collider_2_12: THREE.Mesh
      outer_collider_2_13: THREE.Mesh
      outer_collider_2_14: THREE.Mesh
      outer_collider_2_15: THREE.Mesh
      outer_collider_2_16: THREE.Mesh
      floor_center_rail_1: THREE.Mesh
      floor_center_rail_2: THREE.Mesh
      floor_center_rail_3: THREE.Mesh
      floor_center_rail_4: THREE.Mesh
      floor_center_rail_5: THREE.Mesh
      floor_center_rail_6: THREE.Mesh
      floor_center_rail_7: THREE.Mesh
      floor_center_rail_8: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      Exterior: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/ship.glb')
</script>

{#if $gltf}
  <T is={ref} dispose={false} {...$$restProps}>
    <T.Mesh
      name="sphere"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.sphere.geometry}
      material={$gltf.nodes.sphere.material}
      position={[-2.38, 0.37, 0]}
      userData={{ name: 'sphere' }}
    />
    <T.Mesh
      name="sphere_band"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.sphere_band.geometry}
      material={$gltf.nodes.sphere_band.material}
      position={[-2.38, 0.37, 0]}
      userData={{ name: 'sphere_band' }}
    />
    <T.Mesh
      name="person"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.person.geometry}
      material={$gltf.materials.Material}
      position={[2.24, 4.92, 0]}
      userData={{ name: 'person' }}
    />
    <T.Mesh
      name="exterior_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_top.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_top' }}
    />
    <T.Mesh
      name="exterior_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_bottom.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_bottom' }}
    />
    <T.Mesh
      name="exterior_middle_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_middle_bottom.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_middle_bottom' }}
    />
    <T.Mesh
      name="floor_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_top.geometry}
      material={$gltf.materials.Material}
      position={[0, 3.87, 0]}
      userData={{ name: 'floor_top' }}
    />
    <T.Mesh
      name="floor_center"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center.geometry}
      material={$gltf.materials.Material}
      position={[0, -0.29, 0]}
      userData={{ name: 'floor_center' }}
    />
    <T.Mesh
      name="stasis_chamber"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.stasis_chamber.geometry}
      material={$gltf.materials.Material}
      position={[0, 5.43, -4.32]}
      userData={{ name: 'stasis_chamber' }}
    />
    <T.Mesh
      name="floor_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_bottom.geometry}
      material={$gltf.materials.Material}
      position={[0, -4.13, 0]}
      userData={{ name: 'floor_bottom' }}
    />
    <T.Mesh
      name="exterior_middle_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_middle_top.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_middle_top' }}
    />
    <T.Mesh
      name="floor_top_railing"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_top_railing.geometry}
      material={$gltf.materials.Material}
      position={[0, 3.87, 0]}
      userData={{ name: 'floor_top_railing' }}
    />
    <T.Mesh
      name="console"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.console.geometry}
      material={$gltf.materials.Material}
      position={[4.77, 4.63, -0.09]}
      userData={{ name: 'console' }}
    />
    <T.Mesh
      name="console_screen"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.console_screen.geometry}
      material={$gltf.nodes.console_screen.material}
      position={[4.94, 5.15, -0.09]}
      userData={{ name: 'console_screen' }}
    />
    <T.Mesh
      name="ladder"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.ladder.geometry}
      material={$gltf.nodes.ladder.material}
      position={[0, 4.08, 0.86]}
      scale={0.02}
      userData={{ name: 'ladder' }}
    />
    <T.Mesh
      name="elevator_platform"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.elevator_platform.geometry}
      material={$gltf.materials.Material}
      position={[0, 3.83, 0]}
      userData={{ name: 'elevator_platform' }}
    />
    <T.Mesh
      name="sentry"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.sentry.geometry}
      material={$gltf.materials.Material}
      position={[0, -0.29, 0]}
      userData={{ name: 'sentry' }}
    />
    <T.Mesh
      name="outer_collider_3_1"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_1.geometry}
      material={$gltf.nodes.outer_collider_3_1.material}
      userData={{ name: 'outer_collider_3_1' }}
    />
    <T.Mesh
      name="outer_collider_3_2"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_2.geometry}
      material={$gltf.nodes.outer_collider_3_2.material}
      userData={{ name: 'outer_collider_3_2' }}
    />
    <T.Mesh
      name="outer_collider_3_3"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_3.geometry}
      material={$gltf.nodes.outer_collider_3_3.material}
      userData={{ name: 'outer_collider_3_3' }}
    />
    <T.Mesh
      name="outer_collider_3_4"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_4.geometry}
      material={$gltf.nodes.outer_collider_3_4.material}
      userData={{ name: 'outer_collider_3_4' }}
    />
    <T.Mesh
      name="outer_collider_3_5"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_5.geometry}
      material={$gltf.nodes.outer_collider_3_5.material}
      userData={{ name: 'outer_collider_3_5' }}
    />
    <T.Mesh
      name="outer_collider_3_6"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_6.geometry}
      material={$gltf.nodes.outer_collider_3_6.material}
      userData={{ name: 'outer_collider_3_6' }}
    />
    <T.Mesh
      name="outer_collider_3_7"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_7.geometry}
      material={$gltf.nodes.outer_collider_3_7.material}
      userData={{ name: 'outer_collider_3_7' }}
    />
    <T.Mesh
      name="outer_collider_3_8"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_8.geometry}
      material={$gltf.nodes.outer_collider_3_8.material}
      userData={{ name: 'outer_collider_3_8' }}
    />
    <T.Mesh
      name="outer_collider_3_9"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_9.geometry}
      material={$gltf.nodes.outer_collider_3_9.material}
      userData={{ name: 'outer_collider_3_9' }}
    />
    <T.Mesh
      name="outer_collider_3_10"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_10.geometry}
      material={$gltf.nodes.outer_collider_3_10.material}
      userData={{ name: 'outer_collider_3_10' }}
    />
    <T.Mesh
      name="outer_collider_3_11"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_11.geometry}
      material={$gltf.nodes.outer_collider_3_11.material}
      userData={{ name: 'outer_collider_3_11' }}
    />
    <T.Mesh
      name="outer_collider_3_12"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_12.geometry}
      material={$gltf.nodes.outer_collider_3_12.material}
      userData={{ name: 'outer_collider_3_12' }}
    />
    <T.Mesh
      name="outer_collider_3_13"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_13.geometry}
      material={$gltf.nodes.outer_collider_3_13.material}
      userData={{ name: 'outer_collider_3_13' }}
    />
    <T.Mesh
      name="outer_collider_3_14"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_14.geometry}
      material={$gltf.nodes.outer_collider_3_14.material}
      userData={{ name: 'outer_collider_3_14' }}
    />
    <T.Mesh
      name="outer_collider_3_15"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_15.geometry}
      material={$gltf.nodes.outer_collider_3_15.material}
      userData={{ name: 'outer_collider_3_15' }}
    />
    <T.Mesh
      name="outer_collider_3_16"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_3_16.geometry}
      material={$gltf.nodes.outer_collider_3_16.material}
      userData={{ name: 'outer_collider_3_16' }}
    />
    <T.Mesh
      name="collider_rail_1"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_1.geometry}
      material={$gltf.nodes.collider_rail_1.material}
      userData={{ name: 'collider_rail_1' }}
    />
    <T.Mesh
      name="collider_rail_2"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_2.geometry}
      material={$gltf.nodes.collider_rail_2.material}
      userData={{ name: 'collider_rail_2' }}
    />
    <T.Mesh
      name="collider_rail_3"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_3.geometry}
      material={$gltf.nodes.collider_rail_3.material}
      userData={{ name: 'collider_rail_3' }}
    />
    <T.Mesh
      name="collider_rail_4"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_4.geometry}
      material={$gltf.nodes.collider_rail_4.material}
      userData={{ name: 'collider_rail_4' }}
    />
    <T.Mesh
      name="collider_rail_5"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_5.geometry}
      material={$gltf.nodes.collider_rail_5.material}
      userData={{ name: 'collider_rail_5' }}
    />
    <T.Mesh
      name="collider_rail_6"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_6.geometry}
      material={$gltf.nodes.collider_rail_6.material}
      userData={{ name: 'collider_rail_6' }}
    />
    <T.Mesh
      name="collider_rail_7"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_7.geometry}
      material={$gltf.nodes.collider_rail_7.material}
      userData={{ name: 'collider_rail_7' }}
    />
    <T.Mesh
      name="collider_rail_8"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_8.geometry}
      material={$gltf.nodes.collider_rail_8.material}
      userData={{ name: 'collider_rail_8' }}
    />
    <T.Mesh
      name="collider_rail_9"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_9.geometry}
      material={$gltf.nodes.collider_rail_9.material}
      userData={{ name: 'collider_rail_9' }}
    />
    <T.Mesh
      name="collider_rail_10"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_10.geometry}
      material={$gltf.nodes.collider_rail_10.material}
      userData={{ name: 'collider_rail_10' }}
    />
    <T.Mesh
      name="collider_rail_11"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_11.geometry}
      material={$gltf.nodes.collider_rail_11.material}
      userData={{ name: 'collider_rail_11' }}
    />
    <T.Mesh
      name="collider_rail_12"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_12.geometry}
      material={$gltf.nodes.collider_rail_12.material}
      userData={{ name: 'collider_rail_12' }}
    />
    <T.Mesh
      name="collider_rail_13"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_13.geometry}
      material={$gltf.nodes.collider_rail_13.material}
      userData={{ name: 'collider_rail_13' }}
    />
    <T.Mesh
      name="collider_rail_14"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.collider_rail_14.geometry}
      material={$gltf.nodes.collider_rail_14.material}
      userData={{ name: 'collider_rail_14' }}
    />
    <T.Mesh
      name="outer_collider_2_1"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_1.geometry}
      material={$gltf.nodes.outer_collider_2_1.material}
      userData={{ name: 'outer_collider_2_1' }}
    />
    <T.Mesh
      name="outer_collider_2_2"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_2.geometry}
      material={$gltf.nodes.outer_collider_2_2.material}
      userData={{ name: 'outer_collider_2_2' }}
    />
    <T.Mesh
      name="outer_collider_2_3"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_3.geometry}
      material={$gltf.nodes.outer_collider_2_3.material}
      userData={{ name: 'outer_collider_2_3' }}
    />
    <T.Mesh
      name="outer_collider_2_4"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_4.geometry}
      material={$gltf.nodes.outer_collider_2_4.material}
      userData={{ name: 'outer_collider_2_4' }}
    />
    <T.Mesh
      name="outer_collider_2_5"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_5.geometry}
      material={$gltf.nodes.outer_collider_2_5.material}
      userData={{ name: 'outer_collider_2_5' }}
    />
    <T.Mesh
      name="outer_collider_2_6"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_6.geometry}
      material={$gltf.nodes.outer_collider_2_6.material}
      userData={{ name: 'outer_collider_2_6' }}
    />
    <T.Mesh
      name="outer_collider_2_7"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_7.geometry}
      material={$gltf.nodes.outer_collider_2_7.material}
      userData={{ name: 'outer_collider_2_7' }}
    />
    <T.Mesh
      name="outer_collider_2_8"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_8.geometry}
      material={$gltf.nodes.outer_collider_2_8.material}
      userData={{ name: 'outer_collider_2_8' }}
    />
    <T.Mesh
      name="outer_collider_2_9"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_9.geometry}
      material={$gltf.nodes.outer_collider_2_9.material}
      userData={{ name: 'outer_collider_2_9' }}
    />
    <T.Mesh
      name="outer_collider_2_10"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_10.geometry}
      material={$gltf.nodes.outer_collider_2_10.material}
      userData={{ name: 'outer_collider_2_10' }}
    />
    <T.Mesh
      name="outer_collider_2_11"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_11.geometry}
      material={$gltf.nodes.outer_collider_2_11.material}
      userData={{ name: 'outer_collider_2_11' }}
    />
    <T.Mesh
      name="outer_collider_2_12"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_12.geometry}
      material={$gltf.nodes.outer_collider_2_12.material}
      userData={{ name: 'outer_collider_2_12' }}
    />
    <T.Mesh
      name="outer_collider_2_13"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_13.geometry}
      material={$gltf.nodes.outer_collider_2_13.material}
      userData={{ name: 'outer_collider_2_13' }}
    />
    <T.Mesh
      name="outer_collider_2_14"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_14.geometry}
      material={$gltf.nodes.outer_collider_2_14.material}
      userData={{ name: 'outer_collider_2_14' }}
    />
    <T.Mesh
      name="outer_collider_2_15"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_15.geometry}
      material={$gltf.nodes.outer_collider_2_15.material}
      userData={{ name: 'outer_collider_2_15' }}
    />
    <T.Mesh
      name="outer_collider_2_16"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.outer_collider_2_16.geometry}
      material={$gltf.nodes.outer_collider_2_16.material}
      userData={{ name: 'outer_collider_2_16' }}
    />
    <T.Mesh
      name="floor_center_rail_1"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_1.geometry}
      material={$gltf.materials.Material}
      position={[2.59, -0.26, 0]}
      userData={{ name: 'floor_center_rail_1' }}
    />
    <T.Mesh
      name="floor_center_rail_2"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_2.geometry}
      material={$gltf.materials.Material}
      position={[1.68, -0.26, -1.68]}
      userData={{ name: 'floor_center_rail_2' }}
    />
    <T.Mesh
      name="floor_center_rail_3"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_3.geometry}
      material={$gltf.materials.Material}
      position={[0, -0.26, -2.59]}
      userData={{ name: 'floor_center_rail_3' }}
    />
    <T.Mesh
      name="floor_center_rail_4"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_4.geometry}
      material={$gltf.materials.Material}
      position={[-1.83, -0.26, -1.83]}
      userData={{ name: 'floor_center_rail_4' }}
    />
    <T.Mesh
      name="floor_center_rail_5"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_5.geometry}
      material={$gltf.materials.Material}
      position={[-2.38, -0.26, 0]}
      userData={{ name: 'floor_center_rail_5' }}
    />
    <T.Mesh
      name="floor_center_rail_6"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_6.geometry}
      material={$gltf.materials.Material}
      position={[-1.83, -0.26, 1.83]}
      userData={{ name: 'floor_center_rail_6' }}
    />
    <T.Mesh
      name="floor_center_rail_7"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_7.geometry}
      material={$gltf.materials.Material}
      position={[0, -0.26, 2.38]}
      userData={{ name: 'floor_center_rail_7' }}
    />
    <T.Mesh
      name="floor_center_rail_8"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center_rail_8.geometry}
      material={$gltf.materials.Material}
      position={[1.68, -0.26, 1.68]}
      userData={{ name: 'floor_center_rail_8' }}
    />

    <slot {ref} />
  </T>
{/if}
