<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 public/glb/ship.glb --output src/models/ship.svelte --types --keepnames --meta --shadows --debug
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      person: THREE.Mesh
      exterior_top: THREE.Mesh
      exterior_bottom: THREE.Mesh
      exterior_middle_bottom: THREE.Mesh
      floor_top: THREE.Mesh
      floor_center: THREE.Mesh
      stasis_chamber: THREE.Mesh
      floor_bottom: THREE.Mesh
      exterior_middle_top: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      Exterior: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('/ship.glb')
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="person"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.person.geometry}
      material={$gltf.materials.Material}
      position={[0.49, 4.79, 0]}
      userData={{ name: 'person' }}
    />
    <T.Mesh
      name="exterior_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_top.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_top' }}
    />
    <T.Mesh
      name="exterior_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_bottom.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_bottom' }}
    />
    <T.Mesh
      name="exterior_middle_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_middle_bottom.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_middle_bottom' }}
    />
    <T.Mesh
      name="floor_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_top.geometry}
      material={$gltf.materials.Material}
      position={[0, 3.87, 0]}
      userData={{ name: 'floor_top' }}
    />
    <T.Mesh
      name="floor_center"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_center.geometry}
      material={$gltf.materials.Material}
      position={[0, -0.29, 0]}
      userData={{ name: 'floor_center' }}
    />
    <T.Mesh
      name="stasis_chamber"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.stasis_chamber.geometry}
      material={$gltf.materials.Material}
      position={[-2, 5.35, 0]}
      userData={{ name: 'stasis_chamber' }}
    />
    <T.Mesh
      name="floor_bottom"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.floor_bottom.geometry}
      material={$gltf.materials.Material}
      position={[0, -4.13, 0]}
      userData={{ name: 'floor_bottom' }}
    />
    <T.Mesh
      name="exterior_middle_top"
      castShadow
      receiveShadow
      geometry={$gltf.nodes.exterior_middle_top.geometry}
      material={$gltf.materials.Exterior}
      userData={{ name: 'exterior_middle_top' }}
    />

    <slot {ref} />
  </Three>
{/if}
