<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.2 public/glb/ship.glb --output src/models/ship.svelte --types --keepnames --meta --shadows --debug
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      mesh_0: THREE.Mesh
      mesh_0_1: THREE.Mesh
      mesh_0_2: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      Exterior: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/ship.glb')
</script>

{#if $gltf}
  <T is={ref} dispose={false} {...$$restProps}>
    <T.Group position={[-8.25, -8.25, -8.25]} scale={0}>
      <T.Mesh
        name="mesh_0"
        castShadow
        receiveShadow
        geometry={$gltf.nodes.mesh_0.geometry}
        material={$gltf.materials.Material}
      />
      <T.Mesh
        name="mesh_0_1"
        castShadow
        receiveShadow
        geometry={$gltf.nodes.mesh_0_1.geometry}
        material={$gltf.materials.Exterior}
      />
      <T.Mesh
        name="mesh_0_2"
        castShadow
        receiveShadow
        geometry={$gltf.nodes.mesh_0_2.geometry}
        material={$gltf.nodes.mesh_0_2.material}
      />
    </T.Group>

    <slot {ref} />
  </T>
{/if}
