export type ActionName =
| 'Man_Clapping'
| 'Man_Death'
| 'Man_Idle'
| 'Man_Jump'
| 'Man_Punch'
| 'Man_Roll'
| 'Man_Run'
| 'Man_RunningJump'
| 'Man_Sitting'
| 'Man_Standing'
| 'Man_SwordSlash'
| 'Man_Walk'
